export const menu = {
  layout: [
    {
      id: "module1",
      title: "Module 1",
      type: "module",
      icon: "flaticon2-checking",
      url: "/module1",
      role: [1, 2, 3],
      subMenus: [
        {
          id: "menu-item-1",
          title: "Page1",
          type: "item",
          icon: "file",
          url: "/module1/page1",
          role: [1, 2, 3],
        },
        {
          id: "admin_page_0132",
          title: "Divider 1",
          type: "divider",
          role: [1, 2, 3],
        },
        {
          id: "parent-menu-1",
          title: "Parent Menu 1",
          type: "item",
          icon: "file",
          url: "/module1/division",
          role: [1, 2, 3],
          children: [
            {
              id: "child-1",
              title: "Child 1",
              type: "item",
              icon: "file",
              url: "/module1/division/page2",
              role: [1, 2, 3],
            },
            {
              id: "child-parent-1",
              title: "Child Parent 1",
              type: "item",
              icon: "file",
              url: "/module1/division/division2",
              role: [1, 2, 3],
              children: [
                {
                  id: "child-2",
                  title: "child 2-1",
                  type: "item",
                  icon: "file",
                  url: "/module1/division/division2/page3",
                  role: [1, 2, 3],
                },
                {
                  id: "child-3",
                  title: "child 2-2",
                  type: "item",
                  icon: "file",
                  url: "/module1/division/division2/page4",
                  role: [1, 2, 3],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "surveylist",
      title: "Survey List",
      type: "dynamic_list",
      api: "/api/test/123",
      icon: "flaticon2-crisp-icons",
      url: null,
      role: [1, 2, 3],
    },
  ],
  adminLayout: [
    {
      id: "admin_page_01",
      title: "Workspace",
      type: "module",
      icon: "flaticon2-checking",
      url: "/admin/page1",
      role: [1, 2, 3],
      subMenus: [],
    },
    {
      id: "admin_page_012",
      title: "Divider 1",
      type: "divider",
      role: [1, 2, 3],
    },
    {
      id: "admin_page_02",
      title: "Survey",
      type: "module",
      icon: "flaticon2-checking",
      url: "/admin/page2",
      role: [1, 2, 3],
      subMenus: [],
    },
    {
      id: "Requests",
      title: "Requeset",
      type: "module",
      icon: "flaticon2-checking",
      url: "/admin/module1/",
      role: [1, 2, 3],
      subMenus: [
        {
          id: "single-example-chld1",
          title: "A weird child",
          type: "item",
          icon: "pie-chart",
          url: "/admin/module1/page3",
          role: [1, 2, 3],
        },
        {
          id: "single-example-chld311",
          title: "Childy Parent",
          type: "item",
          icon: "pie-chart",
          url: "/admin/module1/module2",
          role: [1, 2, 3],
          children: [
            {
              id: "child-1",
              title: "Child 1-1",
              type: "item",
              icon: "file",
              url: "/admin/module1/module2/page4",
              role: [1, 2, 3],
            },
          ],
        },
      ],
    },
  ],
};
